version: '3.8'
services:
  db:
    image: mysql:8.0.21 # AWS RDSのバージョンに合わせる
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものに変更(AWS RDSデフォルト設定)
    cap_add:
      - SYS_NICE # プロセス優先度をあげ、警告回避
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3307:3306
    
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      # RAILS_ENV: production
    
    # デバック用設定
    stdin_open: true
    tty: true

    depends_on:
      - db
    
volumes:
  db_data:
